# Notes

# Libraries

In [1]:
# Add this line to suppress errors in the cell
%config Application.run_line_magic = False


In [2]:
import tensorflow as tf 




# from nbclient import NotebookClient, CellExecutionError

# # Load and execute the notebook
# client = NotebookClient(nb, kernel_name="python3", allow_errors=True)
# client.execute()


In [3]:
## high level deep learning API
tf.keras

<KerasLazyLoader (keras_3) keras._tf_keras.keras as keras mode=None>

In [4]:
## low level deep learning API
tf.nn

<module 'tensorflow._api.v2.nn' from 'c:\\Users\\NAIndhraKiranu(893)\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\_api\\v2\\nn\\__init__.py'>

In [5]:
## Auto differentiation
tf.GradientTape

tensorflow.python.eager.backprop.GradientTape

In [6]:
## mathematics, inlcuding linear algebra, signal processing

tf.math 
tf.linalg
tf.signal
tf.random
tf.bitwise

<module 'tensorflow._api.v2.bitwise' from 'c:\\Users\\NAIndhraKiranu(893)\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\_api\\v2\\bitwise\\__init__.py'>

In [7]:
## input output and preprocessing

tf.audio
tf.data
tf.image
tf.io
tf.queue

<module 'tensorflow._api.v2.queue' from 'c:\\Users\\NAIndhraKiranu(893)\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\_api\\v2\\queue\\__init__.py'>

In [8]:
## Visualization with Tensor board

tf.summary.__doc__


'Public API for tf._api.v2.summary namespace\n'

In [9]:
## Deployment and optimization

tf.distribute
tf.saved_model 

tf.autograph
tf.graph_util
tf.lite
tf.quantization
tf.tpu
tf.xla 

<module 'tensorflow._api.v2.xla' from 'c:\\Users\\NAIndhraKiranu(893)\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\_api\\v2\\xla\\__init__.py'>

In [10]:
## special data structures

tf.lookup 
tf.nest
tf.ragged
tf.sets
tf.sparse
tf.strings

<module 'tensorflow._api.v2.strings' from 'c:\\Users\\NAIndhraKiranu(893)\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\_api\\v2\\strings\\__init__.py'>

In [11]:
## miscellanous

tf.experimental
tf.config

<module 'tensorflow._api.v2.config' from 'c:\\Users\\NAIndhraKiranu(893)\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\_api\\v2\\config\\__init__.py'>

# Using TensorFlow like NumPy

In [12]:
t = tf.constant([[1,2,3], [4,5,6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [13]:
t.shape

TensorShape([2, 3])

In [14]:
t.dtype

tf.int32

In [15]:
## indexing just like numpy

t[0,2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [16]:
t[:,1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [17]:
t[..., 1 , tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]])>

In [18]:
tf.newaxis

In [19]:
## all sorts of operations in numpy are available in tensorflow
 
t + 10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [20]:
t - 1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>

In [21]:
t * 5

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5, 10, 15],
       [20, 25, 30]])>

In [22]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [23]:
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [24]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [25]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]])>

In [26]:
## backend working of add()

tf.add(t,10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [27]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [28]:
t.__add__(10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [29]:
## a tensor can also hold a SCALAR value

s = tf.constant(143)
s

<tf.Tensor: shape=(), dtype=int32, numpy=143>

In [30]:
tf.multiply(s, 10)

<tf.Tensor: shape=(), dtype=int32, numpy=1430>

In [31]:
tf.reshape(t, [3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [32]:
tf.reduce_mean(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

# Tensors and NumPy

In [33]:
import numpy as np 

a = np.array([1,2,3])
a 

array([1, 2, 3])

In [34]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [35]:
d = t.numpy()
d

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
d.dtype

dtype('int32')

In [40]:
np.square(t)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [42]:
## expect an error here due to different data types

tf.constant(2) + tf.constant(40.)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 

In [43]:
tf.constant(2.) + tf.constant(40.)  

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [44]:
t2 = tf.constant(40., dtype=tf.float64)
t2 

<tf.Tensor: shape=(), dtype=float64, numpy=40.0>

In [45]:
tf.constant(2.) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

# Variables

In [77]:
v = tf.Variable([[4.,5.,6.], [8.,7.,6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[4., 5., 6.],
       [8., 7., 6.]], dtype=float32)>

In [78]:
v + 1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5., 6., 7.],
       [9., 8., 7.]], dtype=float32)>

In [79]:
v - 2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [6., 5., 4.]], dtype=float32)>

In [80]:
v * 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[40., 50., 60.],
       [80., 70., 60.]], dtype=float32)>

In [81]:
v.assign(2 * v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 8., 10., 12.],
       [16., 14., 12.]], dtype=float32)>

In [82]:
v[0,2].assign(100)


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  8.,  10., 100.],
       [ 16.,  14.,  12.]], dtype=float32)>

In [83]:
v[:,2].assign([0.,1.])


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 8., 10.,  0.],
       [16., 14.,  1.]], dtype=float32)>

In [84]:
v[1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([16., 14.,  1.], dtype=float32)>

In [86]:
## direct assignment here will not work
v[1]=[1,2,3]

TypeError: 'ResourceVariable' object does not support item assignment

# custom loss functions

In [87]:
def huber_fn(y_true, y_pred):
    
    error = y_true - y_pred
    this_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abs(error) - 0.5
    return tf.where(this_small_error, squared_loss, linear_loss)

In [90]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=[28,28]),
    tf.keras.layers.Dense(300, activation='relu', kernel_initializer='he_normal'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(100, activation='relu', kernel_initializer='he_normal'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [92]:
model.compile(loss=huber_fn)

# saving and loading models that contain custom components